### PR TITLE
Update PouchDB to ~5.1.0

### PR DESCRIPTION
**Pull request by filoozom**

### CODE REVIEW

**Comment by tlvince** [comment]
The following spec is failing on Firefox:

```
Angular-wrapped PouchDB event emitters replicate should reject on error FAILED
```

Could you take a look?

**Comment by filoozom** [comment]
It seems like there's a problem with PouchDB.
I'm getting : ```TypeError: setting a property that has only a getter``` on https://github.com/pouchdb/pouchdb/blob/c9143d64dbdd381bf969bd5066d0cee6a4c2fcf7/lib/replicate/replicate.js#L219 after ```abortReplication()``` was called from https://github.com/pouchdb/pouchdb/blob/c9143d64dbdd381bf969bd5066d0cee6a4c2fcf7/lib/replicate/replicate.js#L388.

Does firefox handle catched errors differently than other browsers ? Chrome passes the test without issue.

**Comment by filoozom** [comment]
Actually master fails this test too, so I don't quite know what I should do...

**Comment by tlvince** [comment]
Sure that `master` is failing this also? It doesn't appear to have on Travis at least; a new release wouldn't have been published if so.

**Comment by filoozom** [comment]
Well, I just ran the tests on the v4.0.0 branch, and here are the results : 
```
filoozom:Downloads filoozom$ git clone https://github.com/angular-pouchdb/angular-pouchdb.git
Cloning into 'angular-pouchdb'...
remote: Counting objects: 625, done.
remote: Total 625 (delta 0), reused 0 (delta 0), pack-reused 624
Receiving objects: 100% (625/625), 96.56 KiB | 40.00 KiB/s, done.
Resolving deltas: 100% (344/344), done.
Checking connectivity... done.
filoozom:Downloads filoozom$ cd angular-pouchdb/
filoozom:angular-pouchdb filoozom$ git checkout v4.0.0
Note: checking out 'v4.0.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at f74eff5... feat: PouchDB v5 support
filoozom:angular-pouchdb filoozom$ npm install
npm WARN engine karma-cli@0.0.4: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"4.1.1","npm":"3.3.9"})
npm WARN deprecated eslint-config-tlvince@1.2.0: Unmaintained and unloved. Try eslint-config-standard (or full fat Standard).
npm WARN engine karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (current: {"node":"4.1.1","npm":"3.3.9"})
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN prefer global coffee-script@1.10.0 should be installed with -g

> fsevents@1.0.5 install /Users/filoozom/Downloads/angular-pouchdb/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/filoozom/Downloads/angular-pouchdb/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" is installed via remote

> phantomjs@1.9.19 install /Users/filoozom/Downloads/angular-pouchdb/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/qy/6r3d__f91c3bppr4d2rhrsyr0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...
  [===================================-----] 88% 0.0s
Received 9187K total.
Extracting zip contents
Removing /Users/filoozom/Downloads/angular-pouchdb/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/qy/6r3d__f91c3bppr4d2rhrsyr0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1449136980472/phantomjs-1.9.8-macosx -> /Users/filoozom/Downloads/angular-pouchdb/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/filoozom/Downloads/angular-pouchdb/node_modules/phantomjs/lib/phantom/bin/phantomjs

> ws@0.4.32 install /Users/filoozom/Downloads/angular-pouchdb/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

> angular-pouchdb@ postinstall /Users/filoozom/Downloads/angular-pouchdb
> bower install

bower pouchdb#~5.0.0            cached git://github.com/pouchdb/pouchdb.git#5.0.0
bower pouchdb#~5.0.0          validate 5.0.0 against git://github.com/pouchdb/pouchdb.git#~5.0.0
bower angular#~1.4.1            cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#~1.4.1          validate 1.4.8 against git://github.com/angular/bower-angular.git#~1.4.1
bower angular-mocks#~1.4.1      cached git://github.com/angular/bower-angular-mocks.git#1.4.8
bower angular-mocks#~1.4.1    validate 1.4.8 against git://github.com/angular/bower-angular-mocks.git#~1.4.1
bower angular#~1.4.1           install angular#1.4.8
bower pouchdb#~5.0.0           install pouchdb#5.0.0
bower angular-mocks#~1.4.1     install angular-mocks#1.4.8

angular#1.4.8 bower_components/angular

pouchdb#5.0.0 bower_components/pouchdb

├── bower@1.5.3
├── catw@1.0.1
├── coveralls@2.11.4
├── es5-shim@4.1.13
├── eslint@0.24.1
├── eslint-config-tlvince@1.2.0
├── eslint-plugin-jasmine@1.4.0
├── jasmine-core@2.3.4
├── karma@0.12.37
├── karma-cli@0.0.4
├── karma-coverage@0.2.7
├── karma-firefox-launcher@0.1.6
├── karma-jasmine@0.3.6
├── karma-phantomjs-launcher@0.1.4
├── mkdirp@0.5.1
├── ng-annotate@0.14.1
├── rimraf@2.4.3
├── semantic-release@4.3.5
├── tlvince-blob-shim@1.0.0
└── uglify-js@2.4.24

filoozom:angular-pouchdb filoozom$ npm run test

> angular-pouchdb@ pretest /Users/filoozom/Downloads/angular-pouchdb
> eslint angular-pouchdb.js karma.conf.js test/*.js


> angular-pouchdb@ test /Users/filoozom/Downloads/angular-pouchdb
> karma start

INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [launcher]: Starting browser Firefox
INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket OXZa7T5ySwLfMvwgTAE- with id 3443379
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 9 of 24 SUCCESS (0 secs / 0.242 secs)
Firefox 42.0.0 (Mac OS X 10.11.0) Angular-wrapped PouchDB event emitters replicate should reject on error FAILED
	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL. in /Users/filoozom/Downloads/angular-pouchdb/node_modules/jasmine-core/lib/jasmine-core/jasmine.js (line 1812)
	attemptAsync/timeoutId<@/Users/filoozom/Downloads/angular-pouchdb/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1812:23
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 24 of 24 SUCCESS (0.565 secs / 0.574 secs)
Firefox 42.0.0 (Mac OS X 10.11.0): Executed 24 of 24 (1 FAILED) (8.126 secs / 8.113 secs)
TOTAL: 1 FAILED, 47 SUCCESS

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/4.1.1/bin/node" "/Users/filoozom/.npm-packages/bin/npm" "run" "test"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE
npm ERR! angular-pouchdb@ test: `karma start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-pouchdb@ test script 'karma start'.
npm ERR! This is most likely a problem with the angular-pouchdb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     karma start
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-pouchdb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/filoozom/Downloads/angular-pouchdb/npm-debug.log
```

(I replaced the full ```npm install``` list by a ```npm list --depth=0``` to save 750 lines in the log.)
So I guess it does fail ? At least with Firefox 42.0.0, but it should be the same on 41.0.0 and on linux instead of OS X, considering the failing code didn't change.

**Comment by filoozom** [comment]
I opened an issue on the PouchDB repo : https://github.com/pouchdb/pouchdb/issues/4595

**Comment by tlvince** [comment]
Thanks :+1:

**Comment by filoozom** [comment]
https://github.com/pouchdb/pouchdb/issues/4595 got fixed.
The test should now pass.

**Comment by tlvince** [comment]
Landed in 2c76b89.

**Pull request closed without merging**
