### PR TITLE
Fixed wrap methods after methods with parent

### PR DESCRIPTION
**Pull request by Ti-webdev**
Without this [pouchdb-quick-search](https://github.com/nolanlawson/pouchdb-quick-search) does not work

### CODE REVIEW

**Comment by tlvince** [comment]
I'm not keen on adding support for plugins. Did you see [Does this work with PouchDB plugins?](https://github.com/angular-pouchdb/angular-pouchdb#does-this-work-with-pouchdb-plugins). Or are you suggesting there's a bug in `wrapMethods`?

NB, is `\uffff` *really* a method? Seems an unlikely naming choice.

**Comment by Ti-webdev** [comment]
tlvince, wrapMethods not add any methods after deep

\uffff - it is the last character in utf-8, makes property last in object for most browsers. Boundary value for the test.

**Comment by tlvince** [comment]
Ah, apologies, I was reading this wrongly. Looks good, thanks.

One thing; could you follow [conventional changelog](https://github.com/ajoslin/conventional-changelog/blob/master/CONVENTIONS.md#type) and amend the commit message to something like: `fix: wrap methods after methods with parent`. That way, a patch build will be tagged and released automatically.

**Comment by Ti-webdev** [comment]
tlvince, can you merge?

**Pull request merged**
