### PR TITLE
Make pouchdb-browser dependency more flexible

### PR DESCRIPTION
**Pull request by alxndrsn**
Fix for #114

### CODE REVIEW

**Comment by alxndrsn** [comment]
@tlvince we're using angular-pouchdb at https://github.com/medic and would be happy to help maintain.

cc @SCdF @garethbowen

**Comment by alxndrsn** [comment]
I guess fix is more appropriate as it's changing the style of dependency rather than just updating the version number.

Is the new commit message suitable?

**Comment by tlvince** [comment]
lgtm. Thanks!

**Comment by alxndrsn** [comment]
👍 Thanks!

**Pull request merged**
