### PR TITLE
Update bower.json

### PR DESCRIPTION
**Pull request by dcartertwo**
removed ~ to make versioning more consistent.  the wrong version of angular can be installed sometimes

### CODE REVIEW

**Comment by tbaeg** [comment]
+1

**Comment by gustavohenke** [comment]
The `~` operator is just used to pick the most recent patch version.
If projects follow the [semantic versioning manifest](http://semver.org/), then using `~` is not a problem, so -1 for this.

**Comment by dcartertwo** [comment]
With all due respect @gustavohenke, that is if the package follows semver.  On top of that I have found many times the version to be sent back in inconsistent with the ~ (Official npm documentation states it is 'approximately' the correct version https://docs.npmjs.com/files/package.json).  If you want the most recent version of a package, the same effect can be achieved by using a .x

**Comment by gustavohenke** [comment]
> On top of that I have found many times the version to be sent back in inconsistent with the ~

I have never seen this happen, but even if that comes to happen, I would bother only about Angular which has some history on introducing breaking changes between versions (who remembes the controversial `_` prefix in v1.2.0?)

> Official npm documentation states it is 'approximately' the correct version

[This document specifies the `~` behavior better](https://docs.npmjs.com/misc/semver#tilde-ranges-1-2-3-1-2-1-)

> If you want the most recent version of a package, the same effect can be achieved by using a .x

Nope, this is only the case if you want to consider from `.0`.

**Comment by tlvince** [comment]
@dcartertwo, I understand the sentiment. Authors often don't conform to semver for one reason or another and can unwittingly introduce breaking changes. However, as angular-pouchdb has very little reliance on its dependencies (and indeed, *does* very little), I'm happier to err on the side of semver compliance and not pin dependents. Either way, I defer this decision to Bower's default (via `bower --save [dep]`), which as of 1.3.12 uses `~`.

**Pull request closed without merging**
